/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef accord_CONSTANTS_H
#define accord_CONSTANTS_H

#include "accord_types.h"

namespace rafdb {

class accordConstants {
 public:
  accordConstants();

};

extern const accordConstants g_accord_constants;

} // namespace

#endif
