/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "accord_constants.h"

namespace rafdb {

const accordConstants g_accord_constants;

accordConstants::accordConstants() {
}

} // namespace

