/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef rafdbservice_CONSTANTS_H
#define rafdbservice_CONSTANTS_H

#include "rafdbservice_types.h"

namespace rafdb {

class rafdbserviceConstants {
 public:
  rafdbserviceConstants();

};

extern const rafdbserviceConstants g_rafdbservice_constants;

} // namespace

#endif
