/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "rafdbservice_constants.h"

namespace rafdb {

const rafdbserviceConstants g_rafdbservice_constants;

rafdbserviceConstants::rafdbserviceConstants() {
}

} // namespace

